room: 
  - name: "TERAPI1"

cameras:
  - name: "CAM1"
    hostname: "172.24.135.80"
    username: "uniklinik"
    password: "xJBml4nVqubV"
  - name: "CAM2"
    hostname: "172.24.135.81"
    username: ""
    password: ""
    
server:
  port: 8081
  host: "localhost"
  
ltc:
  filePath: "./assets/LTC_01000000_120mins_30fps_44100x16.wav"
  preRollSeconds: 5
